# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=64)),
                ('Author', models.CharField(default='', max_length=32)),
                ('ISBN', models.CharField(default='', max_length=32)),
                ('Publisher', models.CharField(default='', max_length=32)),
                ('Pub_Time', models.DateField(null=True)),
                ('Pages', models.IntegerField(null=True)),
                ('Description', models.TextField(null=True)),
                ('Available', models.BooleanField(default=1)),
                ('Position', models.CharField(default='A-101', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=16)),
                ('PWD', models.CharField(max_length=16)),
                ('Active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64)),
                ('ISBN', models.CharField(max_length=32)),
                ('Modified_time', models.DateTimeField(auto_now=True)),
                ('Status', models.NullBooleanField()),
                ('Book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyLMS.Book')),
                ('Reader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyLMS.Reader')),
            ],
        ),
    ]
