# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsAvailable', models.IntegerField(auto_created=True, default=1, max_length=1)),
                ('Title', models.CharField(default='Undefine', max_length=32)),
                ('Author', models.CharField(default='Undefine', max_length=32)),
                ('ISBN', models.CharField(default='Undefine', max_length=32)),
                ('Publisher', models.CharField(default='Undefine', max_length=32)),
                ('Pub_Time', models.DateTimeField(null=True)),
                ('Pages', models.IntegerField(null=True)),
                ('Description', models.TextField(null=True)),
            ],
        ),
    ]
