# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='IsAvailable',
            field=models.IntegerField(auto_created=True, default=1),
        ),
    ]
