# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0002_auto_20171018_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
