# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0002_auto_20171031_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='ISBN',
        ),
        migrations.RemoveField(
            model_name='record',
            name='Title',
        ),
    ]
