# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0003_auto_20171018_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='IsAvailable',
        ),
        migrations.AddField(
            model_name='book',
            name='Number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='Position',
            field=models.CharField(default='A-101', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='Pub_Time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Publisher',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(default='', max_length=32),
        ),
    ]
