# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0004_auto_20171018_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Position',
            field=models.CharField(default='A-101', max_length=8),
        ),
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
