# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0004_auto_20171031_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('TOCHECK', 'TOCHECK'), ('BORROWED', 'BORROWED'), ('RETURNED', 'RETURNED')], default='TOCHECK', max_length=16),
        ),
    ]
