# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0005_auto_20171018_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=64)),
                ('Password', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
