# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0008_auto_20171031_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('WAITFORCHECK', 'WAITFORCHECK'), ('BORROWED', 'BORROWED'), ('RETURNED', 'RETURNED'), ('TURNDOWN', 'TURNDOWN')], default='WAITFORCHECK', max_length=16),
        ),
    ]
