# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0009_auto_20171101_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='The_Book', to='MyLMS.Book'),
        ),
    ]
