# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0010_auto_20171101_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='Active',
            field=models.BooleanField(default=0),
        ),
    ]
