# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0011_auto_20171112_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('WAITFORCHECK', 'WAITFORCHECK'), ('BORROWED', 'BORROWED'), ('RETURNED', 'RETURNED'), ('TURNDOWN', 'TURNDOWN'), ('DEMAGE', 'DEMAGE')], default='WAITFORCHECK', max_length=16),
        ),
    ]
