# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0012_auto_20171115_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddbyISBN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=35, max_digits=4),
        ),
    ]
