# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0013_auto_20171115_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Fine_ID')),
                ('Begin_time', models.DateTimeField(null=True)),
                ('End_time', models.DateTimeField(null=True)),
                ('Reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyLMS.Reader')),
            ],
        ),
    ]
