# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0017_auto_20171115_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finestatistic',
            name='Totalfine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
