# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0018_auto_20171115_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finestatistic',
            old_name='Totalfine',
            new_name='TotalFine',
        ),
        migrations.AddField(
            model_name='addbyisbn',
            name='ISBN',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='addbyisbn',
            name='Number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addbyisbn',
            name='Position',
            field=models.CharField(default='A-101', max_length=8),
        ),
        migrations.AddField(
            model_name='addbyisbn',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='addbyisbn',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AddRecord_ID'),
        ),
    ]
