# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0019_auto_20171115_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='StudentCard',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
