# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLMS', '0020_reader_studentcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='StudentCard',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
